language: node_js
node_js:
  - '0.10'
branches:
  only:
    - dev
before_install:
    - npm install -g grunt-cli
before_script:
    - bower install
notifications:
  slack: pagu:z9AxvjaLknWFUI5SAUtzgma2